### ISSUE TITLE
Mobitec protocol

### ISSUE THREAD

**Issue by bjarnekvae** [datagutten/mobitec-php#1]
Hi!

I have a mobitec 16x28 flip dot display which I want to control from a raspberry pi, but finding the protocol is impossible! Where did you find the protocol?

Hilsener fra Trondheim! :)

**Comment by datagutten** [comment]
I have not been able to find the complete protocol anywhere, but I found a thread here which helped me get started: https://elektronikforumet.com/forum/viewtopic.php?f=2&t=65130&view=next
I also found this code: https://github.com/duffrohde/mobitec-rs485/blob/master/skilt.c

Based on this I was able to write more complete documentation on my web page: http://www.busselektro.no/tips-og-funksjonsbeskrivelser/mobitec-rs485/

**Comment by bjarnekvae** [comment]
There we go!

I used the wrong address, and the the checksum was calculated from the first byte (0xff). I will definitely explore the protocol further and push the python driver to github.

Tusen takk!
